---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bobo.
--- DateTime: 2026/5/13 10:33
---
-----浼樻儬鍗穒d
local voucherId=ARGV[1]
---鐢ㄦ埛id
local userId=ARGV[2]
---璁㈠崟id
local orderId=ARGV[3]
---鏁版嵁key
---搴撳瓨key
local stockKey='seckill:stock:'..voucherId
---璁㈠崟key
local orderKey='seckill:order:'..voucherId
---鑴氭湰涓氬姟
---鍒ゆ柇搴撳瓨鏄惁鍏呰冻
if (tonumber(redis.call('get', stockKey)) <= 0) then
    ---涓嶈冻锛岃繑鍥?
    return 1
end
---瓒筹紝鍒ゆ柇鐢ㄦ埛鏄惁閲嶅涓嬪崟
if (redis.call('sismember', orderKey, userId)==1) then
    ---閲嶅涓嬪崟锛岃繑鍥?
    return 2
end
---鏈笅鍗曪紝鎵ｅ噺搴撳瓨
redis.call('incrby',stockKey,-1)
---灏唘serid瀛樺叆褰撳墠浼樻儬鍗穝et闆嗗悎
redis.call('sadd',orderKey,userId)
---鍙戦€佹秷鎭埌闃熷垪涓?
---杩斿洖0
return 0
