---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bobo.
--- DateTime: 2026/5/12 09:54
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0